# Stage A: install vulkan drivers on fedora
FROM fedora:44 as fedora-vulkan
# Use root user
USER root
# Install vulkan drivers
# See https://podman-desktop.io/docs/podman/gpu
RUN dnf -y install dnf-plugins-core dnf-plugin-versionlock && \
    dnf -y install mesa-vulkan-drivers vulkan-loader-devel vulkan-headers vulkan-tools glslc @development-tools gcc-c++ cmake wget libcurl-devel curl && \
    dnf -y copr enable slp/mesa-libkrun-vulkan && \
    REPOID="copr:copr.fedorainfracloud.org:slp:mesa-libkrun-vulkan" && \
    MESA_VERSION=$(dnf repoquery -q --available --repoid="$REPOID" --latest-limit=1 --qf '%{evr}' mesa-vulkan-drivers 2>/dev/null) && \
    dnf downgrade -y "mesa-vulkan-drivers-${MESA_VERSION}" && \
    dnf versionlock add "mesa-vulkan-drivers-${MESA_VERSION}" && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Stage B: install llama.cpp over fedora
# See https://podman-desktop.io/docs/podman/gpu
FROM fedora-vulkan as llama.cpp
# Set root user
USER root
# TODO Install dependencies + Vulkan libkrun drivers
# Clone into llama.cpp and build llama.cpp
# https://github.com/ggml-org/llama.cpp/blob/master/.devops/vulkan.Dockerfile
RUN git clone https://github.com/ggml-org/llama.cpp.git /llama.cpp && \
    cd /llama.cpp && \
    cmake -B build -DGGML_OPENMP=OFF -DGGML_VULKAN=ON && \
    cmake --build build --config Release -j1 --target llama-cli llama-bench llama-server VERBOSE=1

# Stage C: install llama-swap
FROM fedora:44 as llama-swap
# Set root user
USER root
# Install dependencies
RUN dnf -y install golang nodejs && \
    dnf clean all && \
    rm -rf /var/cache/dnf
# Clone into llama-swap and build llama-swap
RUN git clone https://github.com/mostlygeek/llama-swap.git /llama-swap && \
    cd /llama-swap && \
    make clean all

# Stage D: wire up both llama.cpp and llama-swap
FROM fedora-vulkan
# Setup user, including /homes/llama
RUN useradd -m llama
# Copy llama.cpp in user home
COPY --from=llama.cpp /llama.cpp /homes/llama/llama.cpp
COPY --from=llama-swap /llama-swap /homes/llama/llama-swap
# Set correct user
USER llama
# Set home as working directory
WORKDIR /homes/llama/
# Copy llama-swap configuration
COPY llama-swap.yaml llama-swap.yaml
# Update path to expose llama-cli and llama-swap
# NOTE $PATH gets resolved at build time to host PATH, while
# ${PATH} gets resolved at run time to container PATH.
ENV PATH="llama.cpp/build/bin:llama-swap/build/bin:${PATH}"
# Execute llama.cpp CLI
# -ngl N controls GPU offload:
   # 99 offloads as many transformer layers as possible to the GPU.
   # 0 disables GPU offload, forcing inference on the CPU
# GPU-accelerated (offload up to 99 layers)
CMD [ "llama-cli", "--list-devices" ]
# # TODO Execute llama-swap
# CMD [ "llama-swap", "--config", "llama-swap.yaml", "--listen", "localhost:8080" ]
